/**
 * Renders a syllabus as a PDF using pdfkit.
 *
 * pdfkit builds the document programmatically (text, fonts, positions) and
 * streams the bytes as it goes, so even a long syllabus never sits fully in
 * memory. That makes it a good fit for a small free-tier server, unlike
 * headless-browser approaches that need hundreds of megabytes.
 */

const PDFDocument = require("pdfkit");

/**
 * Section layout for the printed document. Mirrors
 * client/src/components/syllabus/syllabusFields.js; keep the two in sync
 * when adding a field.
 */
const SECTIONS = [
  {
    title: "Course",
    fields: [
      ["courseNumber", "Course Number"],
      ["creditHours", "Credit Hours"],
      ["courseDescription", "Course Description"]
    ]
  },
  {
    title: "Instructor",
    fields: [
      ["instructorName", "Instructor Name"],
      ["emailAddress", "Email Address"],
      ["phoneNumber", "Phone Number"],
      ["officeNumber", "Office Number"],
      ["officeHours", "Office Hours"]
    ]
  },
  {
    title: "Schedule",
    fields: [
      ["meetingTimes", "Meeting Times"],
      ["meetingLocation", "Meeting Location"],
      ["courseSchedule", "Course Schedule"]
    ]
  },
  {
    title: "Materials and Grading",
    fields: [
      ["courseMaterials", "Course Materials"],
      ["gradingScale", "Grading Scale"],
      ["extraInfo", "Extra Information"]
    ]
  }
];

const BLUE = "#2979ff";
const GREY = "#616161";

/**
 * Builds the PDF and returns the readable stream. Pipe it to an HTTP
 * response (or a file) and it starts flowing immediately.
 *
 * @param {object} syllabus - A syllabus document (plain object or Mongoose doc).
 * @returns {PDFDocument} A readable stream of PDF bytes.
 */
function renderSyllabusPdf(syllabus) {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 54, bottom: 54, left: 54, right: 54 },
    info: { Title: syllabus.title, Author: syllabus.instructorName || "SyllaMe" }
  });

  // Title block
  doc.font("Helvetica-Bold").fontSize(22).fillColor("#212121").text(syllabus.title);
  const subtitle = [
    syllabus.courseNumber,
    syllabus.creditHours ? `${syllabus.creditHours} credit hours` : null
  ]
    .filter(Boolean)
    .join("  ·  ");
  if (subtitle) {
    doc.moveDown(0.2).font("Helvetica").fontSize(12).fillColor(GREY).text(subtitle);
  }
  doc.moveDown(0.5);
  doc
    .moveTo(doc.x, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .lineWidth(1.5)
    .strokeColor(BLUE)
    .stroke();
  doc.moveDown(0.8);

  for (const section of SECTIONS) {
    const rows = section.fields
      .map(([key, label]) => [label, syllabus[key]])
      .filter(([, value]) => value !== undefined && value !== null && String(value).trim() !== "");
    if (rows.length === 0) continue;

    doc.font("Helvetica-Bold").fontSize(14).fillColor(BLUE).text(section.title);
    doc.moveDown(0.3);

    for (const [label, value] of rows) {
      doc.font("Helvetica-Bold").fontSize(10.5).fillColor(GREY).text(label);
      doc.font("Helvetica").fontSize(11).fillColor("#212121").text(String(value), { paragraphGap: 2 });
      doc.moveDown(0.4);
    }
    doc.moveDown(0.6);
  }

  // Footer with generation date on the first page (pdfkit adds pages on demand,
  // so a per-page footer would need bufferPages; one stamp is enough here).
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#9e9e9e")
    .text(`Generated by SyllaMe on ${new Date().toDateString()}`, {
      align: "right"
    });

  doc.end();
  return doc;
}

/**
 * Turns a title into a safe download filename: letters, digits, dashes.
 *
 * @param {string} title
 * @returns {string} e.g. "Introduction-to-Databases.pdf"
 */
function pdfFilename(title) {
  const base = String(title || "syllabus")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `${base || "syllabus"}.pdf`;
}

module.exports = { renderSyllabusPdf, pdfFilename };
